try:
    #发生异常
    print(20/0)
finally :
    print("执行 finally 块中的代码")  # 会先执行